#                            ┑(￣▽￣)┍
#              >>>>>>>>>>>>>>>>>>>>>>>>>
#                Fqstalph
#                         Twitter: @fqstalph
#                         Website: github.com/Fqstalph
#               >>>>>>>>>>>>>>>>>>>>>>>>>

# Message 
TeleportMessage: "§aYou have been teleported to {player}"
